name: Build, and Run Java App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Revisa el código desde tu repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configura Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Configura la API Key desde el secreto
      - name: Set environment variable
        run: echo "EXCHANGE_RATE_API_KEY=${{ secrets.EXCHANGE_RATE_API_KEY }}" >> $GITHUB_ENV

      # 4. Construye el proyecto usando Maven
      - name: Build with Maven
        run: mvn clean install


      # 5. Ejecuta la aplicación de consola
      - name: Run Console App
        run: mvn exec:java -Dexec.mainClass="ConsultExchangeRate" -Dexec.args="USD"
